### ISSUE TITLE
Error in Browse

### ISSUE THREAD

**Issue by alfredofranceschetti** [alkresin/HDroidGUI#1]
App crashes if a field in Browse contains symbol : 
example
Name = "Smith John"  is ok
Name = "Smith:John" app crashes

**Comment by alkresin** [comment]
Yes, I see. That's because I pass the row to the Java's ListView with ':' as separators between columns. Not a wise idea :). I'll change this to json or something like this.

**Comment by alkresin** [comment]
Fixed.
