### ISSUE TITLE
Bugs in Browse ?

### ISSUE THREAD

**Issue by alfredofranceschetti** [alkresin/HDroidGUI#2]
I thing that there is a bug in browse because if database, has a ordscope set, recno() return wrong value. 
Please check this samples (your first dbf example with ordscope set) and check toast message when click on browse
Ciao
Franz
# include "hdroidgui.ch"

FUNCTION HDroidMain

   Local oWnd, oLayV, oBrw, cPath
   Local i, arr := {"Petr","Fedor","Alexander","Viktor","Nikolay","Ivan","Anton", ;
      "Boris","Alexey","Andrey","Konstantin","Oleg","Igor","Pavel","Sergey","Mikhail","Dmitry", ;
      "Artem","Nikita","Ilya","Vladimir","Vyacheslav","Efim","Lev","Roman","Semen","Miron","Matvey","Leonid"}

   INIT WINDOW oWnd TITLE "Browse" ON EXIT {||dbCloseAll()}

   MENU
      MENUITEM "Exit" ACTION hd_calljava_s_v( "exit:")
   ENDMENU

   BEGIN LAYOUT oLayV SIZE MATCH_PARENT,MATCH_PARENT

   cPath := hd_HomeDir()
   RDDSETDEFAULT( "DBFCDX" )
   IF !File( cPath+"testa.dbf" )
      dbCreate( cPath+"testa", { {"NAME","C",10,0}, {"NUM","N",4,0}, {"INFO","C",32,0}, {"DINFO","D",8,0} } )

```
  USE ( cPath+"testa" ) New EXCLUSIVE
  FOR i := 1 TO Len(arr)
     APPEND BLANK
     REPLACE NAME WITH arr[i], NUM WITH 1000+i, INFO WITH "Record number "+Ltrim(Str(i)), DINFO WITH Date()+i
  NEXT
```

   ELSE

```
  USE ( cPath+"testa" ) New EXCLUSIVE
  INDEX on NAME to (cpath+"testa")
  ordscope(0,"M")
  ordscope(1,"M")
```

   ENDIF
   GO TOP

   IF !Empty( Alias() )

```
  BROWSE oBrw DBF Alias() HSCROLL ON CLICK {|o,n|hd_toast("Row: "+Ltrim(Str(n))+": "+Trim((o:data)->NAME)+Chr(10)+Dtoc((o:data)->DINFO))}

  oBrw:nRowHeight := 40
  oBrw:AddColumn( HDColumn():New( {|o|(o:data)->NAME}, 120 ) )
  oBrw:AddColumn( HDColumn():New( {|o|Str((o:data)->NUM,4)}, 120 ) )
  oBrw:AddColumn( HDColumn():New( {|o|(o:data)->INFO}, 180 ) )
```

   ENDIF

   END LAYOUT oLayV

   ACTIVATE WINDOW oWnd

   RETURN NIL

**Comment by alfredofranceschetti** [comment]
I forgot to tell you that you have to click on the second or third row to see the error (if you click on the first one and then on the other the reponse is correct) 
Ciao
Franz

**Comment by alkresin** [comment]
Yes, I see.
For now you can use the foolwing trick: just add
   FILTER "NUM>0" 
to your BROWSE command. This dbf will be filtered, respecting current scope and the view will be correct.
If you will need to change the scope, call oBrw:Rebuild("NUM>0"), oBrw:Refresh().

**Comment by alkresin** [comment]
Fixed:
2015-03-29 09:40 UTC+0300 Alexander Kresin alex@belacy.ru
- src/prg/hdbrowse.prg
  ! Problem fixed with scoped data - ordKeyCount() is used now instead of recCount()
