### ISSUE TITLE
Ayuda al Crear Buildall.bat

### ISSUE THREAD

**Issue by msagrero** [alkresin/HDroidGUI#7]
Hola a todos al ejecuar el buildall.bat en el ultimo paso resulta un error, me pueden ayudar a correjirlo?
saludos . 
atte: maurosagrero@hotmail.com

C:\hdroidgui>rem @set ANDROID_JAR=c:\Android\sdk/platforms/android-22/android.jar 
Harbour 3.0.0 (Rev. 16951)
Copyright (c) 1999-2011, http://harbour-project.org/
Compiling 'src\prg\hdmain.prg'...
.
.
.
C:\hdroidgui>c:\Android\android-ndk-r10e\prebuilt\windows\bin\make.exe -f c:\Android\android-ndk-r10e/build/core/build-local.mk   1>a1.out 2>a2.out 

C:\hdroidgui\static>c:\Android\android-ndk-r10e\prebuilt\windows\bin\make.exe -f c:\Android\android-ndk-r10e/build/core/build-local.mk   1>>..\a1.out 2>>..\a2.out 

C:\hdroidgui>copy obj\local\armeabi\libh4droida.a lib\libh4droida.a 
        1 archivo(s) copiado(s).

C:\hdroidgui>call C:\java\jre_8.0.45\bin\java -d32 libs -cp c:\Android\sdk\platforms\android-22\android.jar -sourcepath src src\su\harbour\hDroidGUI*.java 
Error: no se ha encontrado o cargado la clase principal libs

Presione una tecla para continuar . . .

**Comment by alkresin** [comment]
Try to use JRE-7 instead of JRE-8. I've heard that there are some problems with using of JRE-8, but hadn't time yet to investigate them.

**Comment by msagrero** [comment]
Ok Alexander, take your advice
greetings from Mexico
Mauro S.
